In [1]:
import numpy as np
import pandas as pd
print('Hello Capstone Project Course!')

Hello Capstone Project Course!

this notebook will be mainly used for the capstone project

In [2]:
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')[0]
df.head()

  Postal code           Borough                Neighborhood
0         M1A      Not assigned                         NaN
1         M2A      Not assigned                         NaN
2         M3A        North York                   Parkwoods
3         M4A        North York            Victoria Village
4         M5A  Downtown Toronto  Regent Park / Harbourfront

In [7]:
drop_col=df[df['Borough']=='Not assigned'].index
df=df.drop(drop_col,inplace=False)
df

,Postal code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,Regent Park / Harbourfront
5,M6A,North York,Lawrence Manor / Lawrence Heights
6,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government
...,...,...,...
160,M8X,Etobicoke,The Kingsway / Montgomery Road / Old Mill North
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,Business reply mail Processing CentrE
169,M8Y,Etobicoke,Old Mill South / King's Mill Park / Sunnylea /...
178,M8Z,Etobicoke,Mimico NW / The Queensway West / South of Bloo...

In [13]:
df.reset_index(drop=True)
df.rename(columns={'Postal code':'Postalcode'},inplace=True)
df.head()

  Postalcode           Borough                                  Neighborhood
2        M3A        North York                                     Parkwoods
3        M4A        North York                              Victoria Village
4        M5A  Downtown Toronto                    Regent Park / Harbourfront
5        M6A        North York             Lawrence Manor / Lawrence Heights
6        M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government

In [5]:
import sys
!{sys.executable} -m pip install geocoder

Requirement already satisfied: geocoder in c:\users\zhy92\anaconda3\lib\site-packages (1.38.1)
Requirement already satisfied: requests in c:\users\zhy92\anaconda3\lib\site-packages (from geocoder) (2.22.0)
Requirement already satisfied: future in c:\users\zhy92\anaconda3\lib\site-packages (from geocoder) (0.17.1)
Requirement already satisfied: six in c:\users\zhy92\anaconda3\lib\site-packages (from geocoder) (1.12.0)
Requirement already satisfied: ratelim in c:\users\zhy92\anaconda3\lib\site-packages (from geocoder) (0.1.6)
Requirement already satisfied: click in c:\users\zhy92\anaconda3\lib\site-packages (from geocoder) (7.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\zhy92\anaconda3\lib\site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\zhy92\anaconda3\lib\site-packages (from requests->geocoder) (1.24.2)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\zhy92\anaconda3\lib\site-packages (from requests->geocoder) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\zhy92\anaconda3\lib\site-packages (from requests->geocoder) (2019.9.11)
Requirement already satisfied: decorator in c:\users\zhy92\anaconda3\lib\site-packages (from ratelim->geocoder) (4.4.0)

In [6]:
geo_df=pd.read_csv('http://cocl.us/Geospatial_data')
geo_df

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [14]:
geo_df.rename(columns={'Postal Code':'Postalcode'},inplace=True)
df= pd.merge(geo_df, df, on='Postalcode')

In [17]:
geo_data=df[['Postalcode','Borough','Neighborhood','Latitude','Longitude']]

In [19]:
geo_data

,Postalcode,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,Malvern / Rouge,43.806686,-79.194353
1,M1C,Scarborough,Rouge Hill / Port Union / Highland Creek,43.784535,-79.160497
2,M1E,Scarborough,Guildwood / Morningside / West Hill,43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,Kingsview Village / St. Phillips / Martin Grov...,43.688905,-79.554724
101,M9V,Etobicoke,South Steeles / Silverstone / Humbergate / Jam...,43.739416,-79.588437
102,M9W,Etobicoke,Northwest,43.706748,-79.594054